export const types = Object.freeze({
    // Sync
    USER_FILL: 'USER_FILL',
    USER_START_FETCHING: 'USER_START_FETCHING',
    USER_STOP_FETCHING: 'USER_STOP_FETCHING',
    USER_SET_FETCHING_ERROR: 'USER_SET_FETCHING_ERROR',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',
    USER_LOGOUT: 'USER_LOGOUT',
    // Async
    USER_REGISTER_ASYNC: 'USER_REGISTER_ASYNC',
    USER_LOGIN_ASYNC: 'USER_LOGIN_ASYNC',
    USER_LOGOUT_ASYNC: 'USER_LOGOUT_ASYNC',
    USER_GET_ME_ASYNC: 'USER_GET_ME_ASYNC',
    USER_UPDATE_ME_ASYNC: 'USER_UPDATE_ME_ASYNC'
});
