export const types = Object.freeze({
    // Sync
    TRACKER_FILL_SCORE: 'TRACKER_FILL_SCORE',
    TRACKER_START_FETCHING: 'TRACKER_START_FETCHING',
    TRACKER_STOP_FETCHING: 'TRACKER_STOP_FETCHING',
    TRACKER_SET_FETCHING_ERROR: 'TRACKER_SET_FETCHING_ERROR',
    TRACKER_FILL_RECORD: 'TRACKER_FILL_RECORD',
    // Async
    TRACKER_FETCH_SCORE_ASYNC: 'TRACKER_FETCH_SCORE_ASYNC',
    TRACKER_FETCH_RECORD_ASYNC: 'TRACKER_FETCH_RECORD_ASYNC',
    TRACKER_CREATE_RECORD_ASYNC: 'TRACKER_CREATE_RECORD_ASYNC',
    TRACKER_UPDATE_RECORD_ASYNC: 'TRACKER_UPDATE_RECORD_ASYNC',
    TRACKER_REMOVE_ALL_RECORDS_ASYNC: 'TRACKER_REMOVE_ALL_RECORDS_ASYNC'
});
